# Generated by Django 4.1.2 on 2023-06-14 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormaEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_tuss", models.CharField(max_length=256)),
                ("terminologia", models.CharField(max_length=256)),
                ("forma_de_envio", models.CharField(max_length=256)),
                ("codigo_do_grupo", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="GrupoEnvio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tabela", models.IntegerField()),
                ("codigo", models.CharField(max_length=256)),
                ("grupo", models.CharField(max_length=256)),
                ("dt_inicio_vigencia", models.DateTimeField()),
                ("dt_fim_vigencia", models.DateTimeField(null=True)),
                ("dt_implantacao", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TabelasDominio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_tabela", models.IntegerField()),
                ("descricao", models.CharField(max_length=256)),
                ("dt_inicio_vigencia", models.DateTimeField()),
                ("dt_fim_vigencia", models.DateTimeField(null=True)),
                ("dt_implantacao", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TermoTuss",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo_tuss", models.CharField(max_length=256)),
                ("tabela", models.IntegerField()),
                ("termo", models.TextField()),
                ("dt_inicio_vigencia", models.DateTimeField()),
                ("dt_fim_vigencia", models.DateTimeField(null=True)),
                ("dt_implantacao", models.DateTimeField(null=True)),
            ],
            options={
                "unique_together": {("codigo_tuss", "tabela")},
            },
        ),
        migrations.CreateModel(
            name="UnidadeMedida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sigla", models.CharField(max_length=256)),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeFederacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_detalhada", models.TextField(null=True)),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TipoDocumento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requer_assinatura", models.CharField(max_length=256, null=True)),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Procedimento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_detalhada", models.TextField(blank=True, null=True)),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ModeloRemuneracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_detalhada", models.TextField(null=True)),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Medicamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("apresentacao", models.CharField(max_length=256)),
                ("laboratorio", models.CharField(max_length=256)),
                ("codigo_anvisa", models.CharField(max_length=256)),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Material",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modelo", models.TextField()),
                ("fabricante", models.TextField()),
                ("codigo_anvisa", models.CharField(max_length=256)),
                ("classe_risco", models.CharField(max_length=256)),
                ("nome_tecnico", models.TextField()),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DiariaTaxa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao_detalhada", models.TextField(blank=True, null=True)),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DemaisTerminologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "termo_tuss",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tuss_items.termotuss",
                    ),
                ),
            ],
        ),
    ]
