# Generated by Django 4.1.2 on 2023-05-07 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tabela63',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.IntegerField()),
                ('codigo', models.IntegerField()),
                ('grupo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela64',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabela', models.IntegerField()),
                ('codigo_tuss', models.IntegerField()),
                ('terminologia', models.CharField(max_length=256)),
                ('forma_de_envio', models.CharField(max_length=256)),
                ('codigo_do_grupo', models.IntegerField(null=True)),
                ('descricao_do_grupo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField(null=True)),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela87',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tabela', models.IntegerField()),
                ('descricao', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tabela81',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('requer_assinatura', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='Tabela79',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('descricao_detalhada', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='Tabela60',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('descricao_detalhada', models.CharField(max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='Tabela59',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('sigla', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='Procedimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('descricao_detalhada', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('apresentacao', models.CharField(max_length=256)),
                ('laboratorio', models.CharField(max_length=256)),
                ('codigo_anvisa', models.IntegerField()),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('modelo', models.CharField(max_length=256)),
                ('fabricante', models.CharField(max_length=256)),
                ('codigo_anvisa', models.CharField(max_length=256)),
                ('classe_risco', models.CharField(max_length=256)),
                ('nome_tecnico', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='DiariaTaxa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
                ('descricao_detalhada', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
        migrations.CreateModel(
            name='DemaisTerminologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_tuss', models.IntegerField()),
                ('tabela', models.IntegerField()),
                ('termo', models.CharField(max_length=256)),
                ('dt_inicio_vigencia', models.DateTimeField()),
                ('dt_fim_vigencia', models.DateTimeField(null=True)),
                ('dt_implantacao', models.DateTimeField(null=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('codigo_tuss', 'tabela')},
            },
        ),
    ]
