# Generated by Django 4.1.2 on 2023-07-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tuss_items", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unidadefederacao",
            name="descricao_detalhada",
        ),
        migrations.RemoveField(
            model_name="unidademedida",
            name="sigla",
        ),
        migrations.AddField(
            model_name="unidadefederacao",
            name="sigla",
            field=models.CharField(default="XX", max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unidademedida",
            name="descricao_detalhada",
            field=models.TextField(null=True),
        ),
    ]
