# Generated by Django 4.1.2 on 2023-05-31 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuss_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='fabricante',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='material',
            name='modelo',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome_tecnico',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='apresentacao',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='codigo_anvisa',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='medicamento',
            name='laboratorio',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='tabela64',
            name='codigo_tuss',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='tabela64',
            name='descricao_do_grupo',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='tabela64',
            name='forma_de_envio',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='tabela64',
            name='terminologia',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='tabela87',
            name='descricao',
            field=models.CharField(max_length=512),
        ),
    ]
