# Generated by Django 4.1.2 on 2023-05-31 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuss_items', '0004_alter_material_nome_tecnico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='classe_risco',
            field=models.TextField(max_length=256),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo_anvisa',
            field=models.TextField(max_length=256),
        ),
    ]
