# Generated by Django 4.1.2 on 2023-05-31 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuss_items', '0005_alter_material_classe_risco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='classe_risco',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='material',
            name='codigo_anvisa',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='material',
            name='modelo',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='material',
            name='nome_tecnico',
            field=models.TextField(),
        ),
    ]
