# Generated by Django 4.1.2 on 2023-06-08 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuss_items', '0007_remove_tabela64_descricao_do_grupo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tabela64',
            new_name='FormaEnvio',
        ),
        migrations.RenameModel(
            old_name='Tabela63',
            new_name='GrupoEnvio',
        ),
        migrations.RenameModel(
            old_name='Tabela60',
            new_name='ModeloRemuneracao',
        ),
        migrations.RenameModel(
            old_name='Tabela87',
            new_name='TabelasDominio',
        ),
        migrations.RenameModel(
            old_name='Tabela81',
            new_name='TipoDocumento',
        ),
        migrations.RenameModel(
            old_name='Tabela79',
            new_name='UnidadeFederacao',
        ),
        migrations.RenameModel(
            old_name='Tabela59',
            new_name='UnidadeMedida',
        ),
    ]
